namespace: ejemplo

deployment:
  name: ejemplo-deployment

image:
  name: ejemplo
  repository: localhost:5000/ejemplo/ejemplo
  tag: "latest"
  pullPolicy: IfNotPresent
  containerPort: 8080

replicaCount: 1

service:
  name: ejemplo-service
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  name: ejemplo-ingress
  className: "nginx"
  host: epiis.unsaac.edu.pe
  path: /ejemplo
  pathType: Prefix

envSecretName: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
